language: android

jdk:
 - oraclejdk8

before_install:
 - chmod +x gradlew
 - pip install --user codecov
 - sudo locale-gen

android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.3

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'

script:
  - ./gradlew jacocoTestReport
  - if ! ./gradlew jacocoTestReport; then ./git checkout -b reports/test_fail; ./git add -f ///home/travis/build/volodia-chornenkyy/WhatPulseHelper/app/build/reports/tests/; git commit -m "Failed tests report"; git push; fi
  - ./gradlew assembleDebug

after_success:
  - codecov