language: android

jdk:
 - oraclejdk8

before_install:
 - chmod +x gradlew

android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.3

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
  script:
    # bash gradlew test jacocoTestReport for tests
    - ./gradlew assembleDebug